FROM python:3.11-slim

# Install system dependencies
RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*

# ✅ FIX: Pin numpy<2.0. MLflow 2.12.1 crashes with Numpy 2.0+
RUN pip install --no-cache-dir \
    "numpy<2.0" \
    mlflow==2.12.1 \
    psycopg2-binary \
    boto3

EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]