FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*

# ✅ FIX: Use MLflow 2.12.1
RUN pip install --default-timeout=1000 --no-cache-dir \
    pandas \
    numpy \
    h3 \
    xgboost \
    mlflow==2.12.1 \
    flask \
    python-dotenv \
    joblib \
    scikit-learn \
    psycopg2-binary \
    requests

COPY src/web_app /app
COPY src/utils /app/src/utils 

ENV PYTHONPATH=/app

CMD ["python", "app.py"]