FROM python:3.11-slim

WORKDIR /app

# Disable output buffering to see logs immediately
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*

# Install dependencies (including setuptools)
RUN pip install --default-timeout=1000 --no-cache-dir \
    pandas \
    "numpy<2.0" \
    h3 \
    xgboost \
    mlflow==2.12.1 \
    "protobuf<5.0" \
    flask \
    python-dotenv \
    joblib \
    scikit-learn \
    psycopg2-binary \
    requests \
    setuptools

# Copy source code structure
COPY src/web_app /app
COPY src/utils /app/src/utils 

ENV PYTHONPATH=/app

CMD ["python", "app.py"]